"""new database tables

Revision ID: 06f206d8ca58
Revises: 
Create Date: 2026-04-01 18:51:02.155551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06f206d8ca58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('auth_provider', sa.String(length=20), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('verification_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('datasets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('columns', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('num_rows_raw', sa.Integer(), nullable=True),
    sa.Column('text_column', sa.String(length=100), nullable=True),
    sa.Column('label_column', sa.String(length=100), nullable=True),
    sa.Column('class_distribution_raw', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('class_distribution_preprocessed', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('preprocessing_status', sa.Enum('IDLE', 'RUNNING', 'COMPLETED', 'ERROR', name='preprocessingstatus'), nullable=False),
    sa.Column('preprocessing_error', sa.Text(), nullable=True),
    sa.Column('num_rows_preprocessed', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'READY', 'ERROR', name='datasetstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preprocessed_rows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('preprocessed_text', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('preprocessed_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_preprocessed_rows_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_preprocessed_rows_label'), ['label'], unique=False)

    op.create_table('training_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=True),
    sa.Column('model_type', sa.Enum('MBERT', 'XLMR', name='modeltype'), nullable=False),
    sa.Column('hyperparams', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('split_info', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('current_epoch', sa.Integer(), nullable=True),
    sa.Column('total_epochs', sa.Integer(), nullable=True),
    sa.Column('epoch_logs', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('final_accuracy', sa.Float(), nullable=True),
    sa.Column('final_f1', sa.Float(), nullable=True),
    sa.Column('final_precision', sa.Float(), nullable=True),
    sa.Column('final_recall', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('colab_session_id', sa.String(length=255), nullable=True),
    sa.Column('dataset_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_jobs_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_jobs_status'), ['status'], unique=False)

    op.create_table('trained_models',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('model_type', sa.String(length=20), nullable=False),
    sa.Column('base_model_name', sa.String(length=255), nullable=True),
    sa.Column('label_map', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('num_labels', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('training_config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['training_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trained_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trained_models_job_id'), ['job_id'], unique=False)

    op.create_table('predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('predicted_label', sa.String(length=100), nullable=True),
    sa.Column('predicted_index', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('all_scores', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['trained_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_user_id'))
        batch_op.drop_index(batch_op.f('ix_predictions_model_id'))
        batch_op.drop_index(batch_op.f('ix_predictions_created_at'))

    op.drop_table('predictions')
    with op.batch_alter_table('trained_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trained_models_job_id'))

    op.drop_table('trained_models')
    with op.batch_alter_table('training_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_training_jobs_dataset_id'))

    op.drop_table('training_jobs')
    with op.batch_alter_table('preprocessed_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_preprocessed_rows_label'))
        batch_op.drop_index(batch_op.f('ix_preprocessed_rows_dataset_id'))

    op.drop_table('preprocessed_rows')
    op.drop_table('datasets')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
