"""remove_duplicate_metrics_from_training_jobs

Revision ID: 216d4ef8e672
Revises: 73605057f633
Create Date: 2026-05-21 09:34:55.667551

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "216d4ef8e672"
down_revision = "73605057f633"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("preprocessed_rows", schema=None) as batch_op:
        batch_op.drop_column("updated_at")

    with op.batch_alter_table("training_jobs", schema=None) as batch_op:
        batch_op.drop_column("final_roc_auc")
        batch_op.drop_column("eval_recall")
        batch_op.drop_column("eval_precision")
        batch_op.drop_column("per_class_metrics")
        batch_op.drop_column("final_mcc")
        batch_op.drop_column("final_mean_std")
        batch_op.drop_column("final_f1")
        batch_op.drop_column("eval_weighted_avg")
        batch_op.drop_column("eval_per_class_metrics")
        batch_op.drop_column("macro_avg")
        batch_op.drop_column("eval_accuracy")
        batch_op.drop_column("eval_f1")
        batch_op.drop_column("weighted_avg")
        batch_op.drop_column("final_recall")
        batch_op.drop_column("final_precision")
        batch_op.drop_column("eval_macro_avg")
        batch_op.drop_column("eval_confusion_matrix")
        batch_op.drop_column("confusion_matrix")
        batch_op.drop_column("final_accuracy")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("training_jobs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "final_accuracy",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "confusion_matrix",
                postgresql.JSON(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "eval_confusion_matrix",
                postgresql.JSON(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "eval_macro_avg",
                postgresql.JSON(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "final_precision",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "final_recall",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "weighted_avg",
                postgresql.JSON(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "eval_f1",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "eval_accuracy",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "macro_avg",
                postgresql.JSON(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "eval_per_class_metrics",
                postgresql.JSON(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "eval_weighted_avg",
                postgresql.JSON(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "final_f1",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "final_mean_std",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "final_mcc",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "per_class_metrics",
                postgresql.JSON(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "eval_precision",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "eval_recall",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "final_roc_auc",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )

    with op.batch_alter_table("preprocessed_rows", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "updated_at",
                postgresql.TIMESTAMP(timezone=True),
                autoincrement=False,
                nullable=False,
            )
        )

    # ### end Alembic commands ###
